language: d

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnodave

script:
   - dub test -b unittest-cov --compiler=${DC}
after_success:
   - bash <(curl -s https://codecov.io/bash)
