//dinodave.bufferappender,dinodave.helper,dinodave.nodave,dinodave,dinodave.plc,dinodave.semver,tests.dinodave.helper,tests.dinodave.plc
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "dinodave.bufferappender",
                          "dinodave.helper",
                          "dinodave.nodave",
                          "dinodave",
                          "dinodave.plc",
                          "dinodave.semver",
                          "tests.dinodave.helper",
                          "tests.dinodave.plc"
                          );
}
